version: '3'


services:

  dbPostgres:
    image: postgres:14.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    container_name: ${POSTGRES_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data

