version: '3'


services:

  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile

    image: dav1dlynn/pharmaceutical-distribution:latest
    container_name: pharma-nest
    ports:
      - ${PORT}:${PORT}
    environment:
      STAGE: ${STAGE}
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
  
  dbPostgres:
    image: postgres:14.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    container_name: ${POSTGRES_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data